# Generated by Django 4.0.4 on 2022-05-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='musicID',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='音乐号'),
        ),
    ]
